name: Build docs

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[docs]

      - name: Build docs
        run: mkdocs build

      - name: Deploy docs
        if: |
          github.repository == 'google/bayesnf'
          && github.ref == 'refs/heads/main'
        run: mkdocs gh-deploy --force
